name: internet_state_manager
description: A Flutter package for seamless internet connection management. Automatically detect connectivity changes, handle outages with customizable widgets, and execute logic when the connection is restoredâ€”all with minimal code.
author: MAlazhariy
homepage: https://github.com/MAlazhariy/internet_state_manager
issue_tracker: https://github.com/MAlazhariy/internet_state_manager/issues
version: 1.4.2

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  internet_connection_checker:
  bloc:
  flutter_bloc:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
